chore: added ecr tage fetch step to deploy pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -56,6 +56,26 @@ jobs:
           role-to-assume: ${{ env.AWS_ROLE_ARN }}
           role-session-name: gha-deploy-${{ github.run_id }}
           unset-current-credentials: true
+      
+
+      - name: Fetch latest image tag from ECR
+        id: ecr
+        shell: bash
+        run: |
+          LATEST_TAG=$(aws ecr describe-images \
+            --repository-name petclinic-dev-api-gateway \
+            --region "$AWS_REGION" \
+            --query 'sort_by(imageDetails, &imagePushedAt)[-1].imageTags[0]' \
+            --output text)
+
+          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" = "None" ]; then
+            echo "Could not resolve latest tag from ECR." >&2
+            exit 1
+          fi
+
+          echo "latest_tag=${LATEST_TAG}" >> "$GITHUB_OUTPUT"
+          echo "Resolved latest ECR tag: ${LATEST_TAG}"
+
 
       - name: Resolve deploy context
         id: context
@@ -97,7 +117,7 @@ jobs:
           elif [ -n "${{ github.event.inputs.image_tag }}" ]; then
             IMAGE_TAG="${{ github.event.inputs.image_tag }}"
           else
-            IMAGE_TAG="$(awk '/^  tag: / { print $2; exit }' helm/petclinic/values.yaml)"
+            IMAGE_TAG="${{ steps.ecr.outputs.latest_tag }}"
           fi
 
           if [ -z "$IMAGE_TAG" ]; then
